import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  background: {
    position: 'relative',
    flex: 1,
    backgroundColor: '#0292b1',
  },

  signin: {
    position: 'absolute',
    width: 107,
    height: 75,
    left: 152,
    top: 54,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 25,
    lineHeight: 29,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: 'white',
  },

  email: {
    position: 'absolute',
    left: 66,
    top: 164,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 15,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
    color: 'white',
  },

  input: {
    position: 'absolute',
    width: 279,
    height: 45,
    left: 66,
    top: 200,
    backgroundColor: '#06aace',
  },

  pass: {
    position: 'absolute',
    left: 66,
    top: 275,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 15,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
    color: 'white',
  },

  inputpass: {
    position: 'absolute',
    width: 279,
    height: 45,
    left: 66,
    top: 311,
    backgroundColor: '#06aace',
  },

  forgotpass: {
    position: 'absolute',
    left: 239,
    top: 366,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 13,
    lineHeight: 15,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: 'white',
  },

  login: {
    position: 'absolute',
    width: 279,
    height: 50,
    left: 66,
    top: 450,
    backgroundColor: 'white',
    borderRadius: 50,
  },

  tlogin: {
    position: 'absolute',
    width: 279,
    height: 50,
    top: 15,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 15,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: '#0292B1',
  },

  or: {
    position: 'absolute',
    left: 190,
    top: 520,
    fontStyle: 'normal',
    fontSize: 15,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: 'white',
  },

  fb: {
    position: 'absolute',
    width: 60,
    height: 60,
    left: 133,
    top: 554,
    backgroundColor: 'white',
    borderRadius: 50,
  },

  lfb: {
    position: 'absolute',
    width: 35,
    height: 35,
    left: 12,
    top: 12,
  },

  gg: {
    position: 'absolute',
    width: 60,
    height: 60,
    left: 218,
    top: 554,
    backgroundColor: 'white',
    borderRadius: 50,
  },

  lgg: {
    position: 'absolute',
    width: 35,
    height: 35,
    left: 12,
    top: 12,
  },

  tsignup: {
    position: 'absolute',
    left: 115,
    top: 700,
    fontStyle: 'normal',
    fontSize: 13,
    lineHeight: 15,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: 'white',
  },

  bsignup: {
    position: 'absolute',
    left: 260,
    top: 700,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 13,
    lineHeight: 15,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: 'white',
  },
});
