import {StyleSheet} from 'react-native';

export const styles2 = StyleSheet.create({
  background: {
    position: 'relative',
    flex: 1,
    backgroundColor: '#0292b1',
  },

  signup: {
    position: 'absolute',
    width: 107,
    height: 75,
    left: 152,
    top: 54,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 25,
    lineHeight: 29,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: 'white',
  },

  email: {
    position: 'absolute',
    left: 66,
    top: 130,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 15,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
    color: 'white',
  },

  input: {
    position: 'absolute',
    width: 279,
    height: 45,
    left: 66,
    top: 170,
    backgroundColor: '#06aace',
  },

  tpass: {
    position: 'absolute',
    left: 66,
    top: 235,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 15,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
    color: 'white',
  },

  pass: {
    position: 'absolute',
    width: 279,
    height: 45,
    left: 66,
    top: 275,
    backgroundColor: '#06aace',
  },

  tcpass: {
    position: 'absolute',
    left: 66,
    top: 340,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 15,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
    color: 'white',
  },

  cpass: {
    position: 'absolute',
    width: 279,
    height: 45,
    left: 66,
    top: 380,
    backgroundColor: '#06aace',
  },

  tnope: {
    position: 'absolute',
    left: 66,
    top: 445,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 15,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
    color: 'white',
  },

  nope: {
    position: 'absolute',
    width: 279,
    height: 45,
    left: 66,
    top: 485,
    backgroundColor: '#06aace',
  },

  daftar: {
    position: 'absolute',
    width: 279,
    height: 50,
    left: 66,
    top: 580,
    backgroundColor: 'white',
    borderRadius: 50,
  },

  tdaftar: {
    position: 'absolute',
    width: 279,
    height: 50,
    top: 15,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 15,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: '#0292B1',
  },
  tsignin: {
    position: 'absolute',
    left: 135,
    top: 700,
    fontStyle: 'normal',
    fontSize: 13,
    lineHeight: 15,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: 'white',
  },

  bsignin: {
    position: 'absolute',
    left: 225,
    top: 700,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 13,
    lineHeight: 15,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: 'white',
  },
});
